import { useEffect, useState } from 'react';
import { Alert, Button, Card, Col, Input, Row, Segmented, Space, Tag, Typography } from 'antd';
import { CodeOutlined, PlayCircleOutlined, SendOutlined } from '@ant-design/icons';
import { JAVA_PROBLEMS } from '../java/data';
import { javaService, type JavaRuntimeStatus } from '../java/service';
import { CodeEditor } from '../components/CodeEditor';
import { MarkdownView } from '../components/MarkdownView';
import { OutputPanel } from '../components/OutputPanel';
import { TestCasePanel } from '../components/TestCasePanel';
import type { RunOutcome } from '../types/problem';
import type { SubmissionResult, TestCaseResult } from '../compiler/client';
const { Title, Text } = Typography; const { TextArea } = Input;
export function JavaArenaPage() {
  const [index,setIndex]=useState(0); const problem=JAVA_PROBLEMS[index]; const [code,setCode]=useState(problem.starter_code); const [stdin,setStdin]=useState(problem.test_cases[0].input); const [status,setStatus]=useState<JavaRuntimeStatus>(javaService.getStatus()); const [outcome,setOutcome]=useState<RunOutcome|null>(null); const [submission,setSubmission]=useState<SubmissionResult|null>(null); const [results,setResults]=useState<TestCaseResult[]|null>(null); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<'stdin'|'output'>('output'); const [mode,setMode]=useState<'run'|'submit'>('run');
  useEffect(()=>javaService.subscribe(setStatus),[]); useEffect(()=>{setCode(problem.starter_code);setStdin(problem.test_cases[0].input);setOutcome(null);setSubmission(null);setResults(null);},[problem]);
  const run=async()=>{setBusy(true);setMode('run');try{setOutcome(await javaService.runOnce(code,stdin));setTab('output');}finally{setBusy(false);}}; const submit=async()=>{setBusy(true);setMode('submit');try{const r=await javaService.submit(code,problem.test_cases,x=>setResults(p=>{const a=p?[...p]:[];a[x.index]=x;return a;}));setSubmission(r);setResults(r.cases);setTab('output');}finally{setBusy(false);}};
  return <div className="page"><Card className="hero-card" variant="borderless"><Title level={2}><CodeOutlined/> Java 基础语法靶场 <Tag color="orange">Beta</Tag></Title><Text type="secondary">Java 8 在浏览器本地编译和运行。首批关卡已开放，更多题目将按 Python 靶场的教学标准扩展。</Text></Card><Row gutter={[16,16]} style={{marginTop:16}}><Col xs={24} lg={8}><Card variant="borderless" title="Java 入门"><Space direction="vertical" style={{width:'100%'}}>{JAVA_PROBLEMS.map((p,i)=><Button key={p.id} type={i===index?'primary':'text'} block onClick={()=>setIndex(i)}>{i+1}. {p.title}</Button>)}</Space><div style={{marginTop:16}}><MarkdownView content={problem.description}/></div></Card></Col><Col xs={24} lg={16}><Alert type={status.phase==='failed'?'error':status.phase==='ready'?'success':'info'} showIcon message={status.message} style={{marginBottom:12}}/><Card variant="borderless" styles={{body:{padding:12}}}><Space className="editor-toolbar" style={{width:'100%',justifyContent:'space-between'}} wrap><Space><Tag color="orange">Java 8</Tag><Text type="secondary">Doppio JVM · 浏览器本地运行</Text></Space><Space><Button onClick={()=>setCode(problem.starter_code)}>重置代码</Button><Button icon={<PlayCircleOutlined/>} onClick={run} loading={busy&&mode==='run'}>运行</Button><Button type="primary" icon={<SendOutlined/>} onClick={submit} loading={busy&&mode==='submit'}>提交</Button></Space></Space><div className="editor-wrapper"><CodeEditor language="java" value={code} onChange={setCode} height={400}/></div></Card><Card variant="borderless" styles={{body:{padding:12}}} style={{marginTop:12}}><Segmented value={tab} onChange={x=>setTab(x as 'stdin'|'output')} options={[{value:'stdin',label:'标准输入 (stdin)'},{value:'output',label:'运行结果'}]}/>{tab==='stdin'?<TextArea value={stdin} onChange={e=>setStdin(e.target.value)} rows={6} style={{marginTop:8}}/>:<OutputPanel outcome={outcome} submission={submission} busy={busy} mode={mode} code={code}/>}</Card><Card variant="borderless" styles={{body:{padding:12}}} style={{marginTop:12}}><TestCasePanel testCases={problem.test_cases} results={results} running={busy} onRunAll={submit} onUseAsInput={x=>{setStdin(x.input);setTab('stdin');}}/></Card></Col></Row></div>;
}
